/**
 * Brand mark — single source of truth. GENERATED by scripts/make-brand-assets.mjs.
 * Do not hand-edit: change the geometry in that script and re-run it.
 *
 * The mark is a heart cradled in open hands — the hands are the platform holding
 * a giver's contribution, the heart is the cause. Every path is drawn on a 24x24
 * grid so the same strings feed SVG (site, favicon, OG image) and Path2D (the
 * canvas-rendered fundraiser ID).
 */

/** Open hands: palm, two splayed fingers, two thumbs. Filled as separate
 * subpaths — merging them into one string makes overlaps cancel under the
 * nonzero fill rule and punches holes in the mark. */
export const BRAND_HAND_PATHS: readonly string[] = [
  "M9.52 13.94 L14.48 13.94 A3.6 3.6 0 0 1 18.08 17.53 A3.6 3.6 0 0 1 14.48 20.76 L9.52 20.76 A3.6 3.6 0 0 1 5.92 17.53 A3.6 3.6 0 0 1 9.52 13.94 Z",
  "M6.78 16.79 L3.59 11.69 A1.18 1.18 0 0 1 5.6 10.44 L8.79 15.55 Z",
  "M15.21 15.55 L18.4 10.44 A1.18 1.18 0 0 1 20.41 11.69 L17.22 16.79 Z",
  "M8.74 16.86 L4.03 14.01 A1.36 1.36 0 0 0 2.61 16.34 L7.33 19.19 Z",
  "M16.67 19.19 L21.39 16.34 A1.36 1.36 0 0 0 19.97 14.01 L15.26 16.86 Z",
];

/** Heart, resting in the cup of the hands. Draw it after the hands. */
export const BRAND_HEART_PATH = "M12 13.91 C12 13.91 6.71 10.61 6.71 6.95 C6.71 5.08 8.17 3.54 10.05 3.54 C11 3.54 11.64 4.14 12 4.72 C12.36 4.14 13 3.54 13.95 3.54 C15.83 3.54 17.29 5.08 17.29 6.95 C17.29 10.61 12 13.91 12 13.91 Z";

export const BRAND_GREEN = "#0f7a4d";
export const BRAND_GOLD = "#c8922a";
